### ISSUE TITLE
Evitar bug

### ISSUE THREAD

**Issue by walber-vaz** [T635/P.A.I.F#1]
https://github.com/T635/P.A.I.F/blob/92c496ae70eb22356affce7935ba745ed31aa15f/main.py#L1

Seria melhor você usar #!/usr/bin/env python3.8
assim evitar erro em outro sistema linux.
ou chama no try catch verificando qual OS.

**Comment by t-prado** [comment]
Resolvi o problema, obrigado pela ajuda, e desculpe a demora.
